CREATE TABLE `實價登陸主檔`(
	`編號`  varchar(20) NOT NULL,
	`縣市別`  varchar(20) NULL,
	`鄉鎮市區`  varchar(10) NULL,
	`交易標的`  varchar(500) NULL,
	`土地區段位置建物區段門牌`  varchar (500) NULL,
	`土地移轉總面積平方公尺`  decimal(10, 3) NULL,
	`都市土地使用分區`  varchar(3) NULL,
	`非都市土地使用分區`  varchar(500) NULL,
	`非都市土地使用編定`  varchar(500) NULL,
	`交易年月日`  date  NULL,
	`交易筆棟數`  varchar(12) NULL,
	`移轉層次`  varchar(500) NULL,
	`總樓層數`  varchar(500) NULL,
	`建物型態`  varchar(500) NULL,
	`主要用途`  varchar(500) NULL,
	`主要建材`  varchar(500) NULL,
	`建築完成年月`  date  NULL,
	`建物移轉總面積平方公尺`  decimal(10, 3) NULL,
	`建物現況格局-房`  int  NULL,
	`建物現況格局-廳`  int  NULL,
	`建物現況格局-衛`  int  NULL,
	`建物現況格局-隔間`  varchar(2) NULL,
	`有無管理組織`  varchar(2) NULL,
	`總價元`  bigint  NULL,
	`單價元平方公尺`  int  NULL,
	`車位類別`  varchar (6) NULL,
	`車位移轉總面積平方公尺`  decimal(10, 3) NULL,
	`車位總價元`  int  NULL,
	`備註`  varchar (500) NULL,
	`Create_Date`  datetime NULL,
  PRIMARY KEY (`編號`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;